[package]
name = "ayuyan"
version = "0.1.0"
edition = "2021"
authors = ["OverzealousLotus"]


[dependencies]
dashmap = "5.4.0"
dotenvy = "0.15.7"
poise = "0.5.5"
tinyrand = "0.5.0"
tinyrand-std = "0.5.0"
tinyvec = "1.6.0"

[dependencies.tokio]
version = "1.28"
features = ["macros", "rt-multi-thread"]
