use crate::assets::equipment::{Armour, Material, Weapon};
use crate::assets::equipment::{Armour::*, Material::*, Weapon::*};

/// Array used to store armours.
/// Strength goes from highest being strongest, to lowest being weakest.
pub(crate) const ARMOUR_LOOT: [Material<Armour>; 35] = [
    Steel(Helmet),
    Steel(Chestplate),
    Steel(Gauntlets),
    Steel(Chausses),
    Steel(Grieves),
    CastIron(Helmet),
    CastIron(Chestplate),
    CastIron(Gauntlets),
    CastIron(Chausses),
    CastIron(Grieves),
    WroughtIron(Helmet),
    WroughtIron(Chestplate),
    WroughtIron(Gauntlets),
    WroughtIron(Chausses),
    WroughtIron(Grieves),
    Bronze(Helmet),
    Bronze(Chestplate),
    Bronze(Gauntlets),
    Bronze(Chausses),
    Bronze(Grieves),
    Iron(Helmet),
    Iron(Chestplate),
    Iron(Gauntlets),
    Iron(Chausses),
    Iron(Grieves),
    PigIron(Helmet),
    PigIron(Chestplate),
    PigIron(Gauntlets),
    PigIron(Chausses),
    PigIron(Grieves),
    Brass(Helmet),
    Brass(Chestplate),
    Brass(Gauntlets),
    Brass(Chausses),
    Brass(Grieves),
];

/// Array used to store weaponry.
pub(crate) const WEAPON_LOOT: [Material<Weapon>; 35] = [
    Steel(Shortsword),
    Steel(Longsword),
    Steel(Greatsword),
    Steel(Ultrasword),
    Steel(Mace),
    CastIron(Shortsword),
    CastIron(Longsword),
    CastIron(Greatsword),
    CastIron(Ultrasword),
    CastIron(Mace),
    WroughtIron(Shortsword),
    WroughtIron(Longsword),
    WroughtIron(Greatsword),
    WroughtIron(Ultrasword),
    WroughtIron(Mace),
    Bronze(Shortsword),
    Bronze(Longsword),
    Bronze(Greatsword),
    Bronze(Ultrasword),
    Bronze(Mace),
    Iron(Shortsword),
    Iron(Longsword),
    Iron(Greatsword),
    Iron(Ultrasword),
    Iron(Mace),
    PigIron(Shortsword),
    PigIron(Longsword),
    PigIron(Greatsword),
    PigIron(Ultrasword),
    PigIron(Mace),
    Brass(Shortsword),
    Brass(Longsword),
    Brass(Greatsword),
    Brass(Ultrasword),
    Brass(Mace),
];
