use crate::assets::equipment::{Armour, Elixir, Material, Strength, Weapon};
use crate::assets::equipment::{Armour::*, Iron::*, Material::*, Strength::*, Weapon::*};

/// Array used to store armours.
/// Strength goes from highest being strongest, to lowest being weakest.
pub(crate) const ARMOUR_LOOT: [Material<Armour>; 30] = [
    Steel(Helmet),
    Steel(Chestplate),
    Steel(Gauntlets),
    Steel(Chausses),
    Steel(Grieves),
    IronType(Cast(Helmet)),
    IronType(Cast(Chestplate)),
    IronType(Cast(Gauntlets)),
    IronType(Cast(Chausses)),
    IronType(Cast(Grieves)),
    IronType(Wrought(Helmet)),
    IronType(Wrought(Chestplate)),
    IronType(Wrought(Gauntlets)),
    IronType(Wrought(Chausses)),
    IronType(Wrought(Grieves)),
    Bronze(Helmet),
    Bronze(Chestplate),
    Bronze(Gauntlets),
    Bronze(Chausses),
    Bronze(Grieves),
    IronType(Pig(Helmet)),
    IronType(Pig(Chestplate)),
    IronType(Pig(Gauntlets)),
    IronType(Pig(Chausses)),
    IronType(Pig(Grieves)),
    Brass(Helmet),
    Brass(Chestplate),
    Brass(Gauntlets),
    Brass(Chausses),
    Brass(Grieves),
];

/// Array used to store weaponry.
pub(crate) const WEAPON_LOOT: [Material<Weapon>; 30] = [
    Steel(Shortsword),
    Steel(Longsword),
    Steel(Greatsword),
    Steel(Ultrasword),
    Steel(Mace),
    IronType(Cast(Shortsword)),
    IronType(Cast(Longsword)),
    IronType(Cast(Greatsword)),
    IronType(Cast(Ultrasword)),
    IronType(Cast(Mace)),
    IronType(Wrought(Shortsword)),
    IronType(Wrought(Longsword)),
    IronType(Wrought(Greatsword)),
    IronType(Wrought(Ultrasword)),
    IronType(Wrought(Mace)),
    Bronze(Shortsword),
    Bronze(Longsword),
    Bronze(Greatsword),
    Bronze(Ultrasword),
    Bronze(Mace),
    IronType(Pig(Shortsword)),
    IronType(Pig(Longsword)),
    IronType(Pig(Greatsword)),
    IronType(Pig(Ultrasword)),
    IronType(Pig(Mace)),
    Brass(Shortsword),
    Brass(Longsword),
    Brass(Greatsword),
    Brass(Ultrasword),
    Brass(Mace),
];

/// Array storing Elixirs.
pub(crate) const ELIXIR_LOOT: [Strength<Elixir>; 12] = [
    Potent(Elixir::Tenacity),
    Potent(Elixir::Vigor),
    Potent(Elixir::Vitality),
    Potent(Elixir::Vivacity),
    Nominal(Elixir::Tenacity),
    Nominal(Elixir::Vigor),
    Nominal(Elixir::Vitality),
    Nominal(Elixir::Vivacity),
    Impotent(Elixir::Tenacity),
    Impotent(Elixir::Vigor),
    Impotent(Elixir::Vitality),
    Impotent(Elixir::Vivacity),
];
